### ISSUE TITLE
Exception: Pychop3D failed

### ISSUE THREAD

**Issue by afshawnlotfi** [gregstarr/pychop3d#32]
used pip versions instead of https://www.lfd.uci.edu/~gohlke/pythonlibs versions because I am using Debian docker container instead of Windows:
meshpy==2018.2.1
shapely==1.7.0
rtree==0.8.3

Ran basic ``main.py`` example and got error

```bash
root@34f40a214801:/workspaces/propeller/pychop3d# python main.py 
Using config: examples/bunny_config.yml
Using mesh: examples/Bunny-LowPoly.stl
2020-08-25 23:52:09,946  pychop3d.search  [INFO]  Starting beam search with an instance of <class 'trimesh.base.Trimesh'>
2020-08-25 23:52:10,853  pychop3d.search  [INFO]  normal index: 0, trees for normal: 0, total trees: 0
2020-08-25 23:52:11,374  pychop3d.search  [INFO]  normal index: 1, trees for normal: 0, total trees: 0
2020-08-25 23:52:11,904  pychop3d.search  [INFO]  normal index: 2, trees for normal: 0, total trees: 0
2020-08-25 23:52:12,401  pychop3d.search  [INFO]  normal index: 3, trees for normal: 0, total trees: 0
2020-08-25 23:52:12,900  pychop3d.search  [INFO]  normal index: 4, trees for normal: 0, total trees: 0
2020-08-25 23:52:13,329  pychop3d.search  [INFO]  normal index: 5, trees for normal: 0, total trees: 0
2020-08-25 23:52:13,764  pychop3d.search  [INFO]  normal index: 6, trees for normal: 0, total trees: 0
2020-08-25 23:52:14,242  pychop3d.search  [INFO]  normal index: 7, trees for normal: 0, total trees: 0
2020-08-25 23:52:14,776  pychop3d.search  [INFO]  normal index: 8, trees for normal: 0, total trees: 0
2020-08-25 23:52:15,292  pychop3d.search  [INFO]  normal index: 9, trees for normal: 0, total trees: 0
2020-08-25 23:52:15,862  pychop3d.search  [INFO]  normal index: 10, trees for normal: 0, total trees: 0
2020-08-25 23:52:16,390  pychop3d.search  [INFO]  normal index: 11, trees for normal: 0, total trees: 0
2020-08-25 23:52:16,999  pychop3d.search  [INFO]  normal index: 12, trees for normal: 0, total trees: 0
2020-08-25 23:52:17,528  pychop3d.search  [INFO]  normal index: 13, trees for normal: 0, total trees: 0
2020-08-25 23:52:17,999  pychop3d.search  [INFO]  normal index: 14, trees for normal: 0, total trees: 0
2020-08-25 23:52:18,376  pychop3d.search  [INFO]  normal index: 15, trees for normal: 0, total trees: 0
2020-08-25 23:52:18,741  pychop3d.search  [INFO]  normal index: 16, trees for normal: 0, total trees: 0
2020-08-25 23:52:19,152  pychop3d.search  [INFO]  normal index: 17, trees for normal: 0, total trees: 0
2020-08-25 23:52:19,565  pychop3d.search  [INFO]  normal index: 18, trees for normal: 0, total trees: 0
2020-08-25 23:52:20,021  pychop3d.search  [INFO]  normal index: 19, trees for normal: 0, total trees: 0
2020-08-25 23:52:20,469  pychop3d.search  [INFO]  normal index: 20, trees for normal: 0, total trees: 0
2020-08-25 23:52:20,985  pychop3d.search  [INFO]  normal index: 21, trees for normal: 0, total trees: 0
2020-08-25 23:52:21,444  pychop3d.search  [INFO]  normal index: 22, trees for normal: 0, total trees: 0
2020-08-25 23:52:21,920  pychop3d.search  [INFO]  normal index: 23, trees for normal: 0, total trees: 0
2020-08-25 23:52:22,381  pychop3d.search  [INFO]  normal index: 24, trees for normal: 0, total trees: 0
2020-08-25 23:52:22,772  pychop3d.search  [INFO]  normal index: 25, trees for normal: 0, total trees: 0
2020-08-25 23:52:23,289  pychop3d.search  [INFO]  normal index: 26, trees for normal: 0, total trees: 0
2020-08-25 23:52:23,751  pychop3d.search  [INFO]  normal index: 27, trees for normal: 0, total trees: 0
2020-08-25 23:52:23,752  pychop3d.search  [INFO]  0 valid trees
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    run(starter)
  File "main.py", line 52, in run
    tree = beam_search(starter)
  File "/workspaces/propeller/pychop3d/pychop3d/search.py", line 102, in beam_search
    raise Exception("Pychop3D failed")
Exception: Pychop3D failed
```

my requirements.txt
```
matplotlib
numpy
scipy
pytest
networkx
pyyaml
requests
trimesh
pyglet
meshpy==2018.2.1
shapely==1.7.0
rtree==0.8.3
```
my python version: ``Python 3.7.9``
my pip version: ``pip 20.2.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)``

**Comment by gregstarr** [comment]
Thanks for submitting this issue, I am looking into it now

**Comment by gregstarr** [comment]
Made updates to the installation instructions and the requirements file. Now the example "finishes" but the chops are messed up. I will need to spend more time on this. If you want, you can try following the new instructions and see the result.

**Comment by afshawnlotfi** [comment]
Tried getting blender on linux to see if this would solve anything but still nothing. I am installing Windows in a VM and will let you know what happens.

**Comment by afshawnlotfi** [comment]
With a fresh install of Windows, Blender, and requirements.txt all in a pyenv I get this when I run main.py now:

```
(venv) PS C:\Users\Afshawn Lotfi\Documents\pychop3d> python .\main.py 
Traceback (most recent call last):
File ".\main.py", line 20, in <module>
from pychop3d.search import beam_search 
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\pychop3d\search.py", line 2, in <module>
import trimesh
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\trimesh\__init__.py", line 15, in <module> 
from .base import Trimesh 
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\trimesh\base.py", line 9, in <module>
from . import ray 
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\trimesh\ray\__init__.py", line 1, in <module> 
from .import ray_triangle 
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\trimesh\ray\ray_triangle.py", line 7, in <module>
from .ray_util import contains_points
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\trimesh\ray\ray_util.py", line 4, in <module>
from .. import bounds 
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\trimesh\bounds.py", line 5, in <module>
from . import convex
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\trimesh\convex.py", line 21, in <module>
from scipy import spatial
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\scipy\__init__.py", line 136, in <module>
from . import _distributor_init 
File "C:\Users\Afshawn Lotfi\Documents\pychop3d\venv\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
WinDLL(os.path.abspath(filename))
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__ 
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found 
```
cannot seem to solve it yet. after we figure this out I am going to create a Docker container so we don't have anymore compatibility issues

**Comment by gregstarr** [comment]
That is a scipy issue, it can't find a dll file. I wonder if that has to do with the windows VM. I have no experience using Docker so I can't help with that. Originally you were running in a Debian docker container, and now you are trying a windows docker container? What is your base operating system?

For the scipy issue, can you find the DLL it needs and add the containing directory to your PATH environment variable?

**Comment by afshawnlotfi** [comment]
No this isn't a Windows Docker container, I'm running it in VMWare so should work like a normal Windows system. I'll try solving the scipy issue today

**Comment by afshawnlotfi** [comment]
Also kind of curious about the significance of installing the 3rd party wheel files as opposed to the official pip archives. Just getting a little acclimated to the setup.

**Comment by gregstarr** [comment]
They require compilation of C libraries, something which I always struggle with. I was very happy to find that you can just install these pre-compiled wheels instead, so I figured I would point people to that. I think if you want to compile and install those libraries on your own, that is fine too.

**Comment by gregstarr** [comment]
I found a problem where repeatedly performing the same operation in Blender would yield different results. The operation, which is boolean difference / union in order to add connectors, is now performed repeatedly until the number of vertices in the resulting part **increases**. I tested it out, it seems to work. If we can get your environment properly set up, I think you should be able to run the example.

**Comment by afshawnlotfi** [comment]
do you mind listing all your package versions inside of your pyenv Lib directory. I believe there is just a version conflict. If I get that solved we should be good.

**Comment by gregstarr** [comment]
This is the output of `pip list`:

```
Package            Version
------------------ -------------------
appdirs            1.4.4
atomicwrites       1.4.0
attrs              20.1.0
certifi            2020.6.20
chardet            3.0.4
colorama           0.4.3
cycler             0.10.0
decorator          4.4.2
gmsh-interop       2019.1
idna               2.10
importlib-metadata 1.7.0
iniconfig          1.0.1
kiwisolver         1.2.0
matplotlib         3.3.1
MeshPy             2018.2.1
more-itertools     8.4.0
networkx           2.5
numpy              1.19.1
packaging          20.4
Pillow             7.2.0
pip                20.2.2
pluggy             0.13.1
py                 1.9.0
pyglet             1.5.7
pyparsing          2.4.7
pytest             6.0.1
python-dateutil    2.8.1
pytools            2020.4
PyYAML             5.3.1
requests           2.24.0
Rtree              0.9.4
scipy              1.5.2
setuptools         49.6.0.post20200814
Shapely            1.7.1
six                1.15.0
toml               0.10.1
triangle           20200424
trimesh            3.8.3
urllib3            1.25.10
wheel              0.35.1
wincertstore       0.2
zipp               3.1.0
```

Hope this helps

**Comment by afshawnlotfi** [comment]
Great news, 

updated my requirments.txt:
```
matplotlib==3.3.1
numpy==1.19.1
scipy==1.5.2
pytest==6.0.1
networkx==2.5
pyyaml==5.3.1
requests==2.24.0
trimesh==3.8.3
triangle==20200424
pyglet==1.5.7
meshpy==2018.2.1
shapely==1.7.1
rtree==0.9.4
```
and installed this: ```apt install libspatialindex-dev```

so now it seems like the search finishes successfully, however I get a new Exception:

```
root@da01918aca7d:/workspaces/propeller/pychop3d# python main.py 
Using config: examples/bunny_config.yml
Using mesh: examples/Bunny-LowPoly.stl
2020-08-26 18:32:05,499  pychop3d.search  [INFO]  Starting beam search with an instance of <class 'trimesh.base.Trimesh'>
2020-08-26 18:32:07,799  pychop3d.search  [INFO]  normal index: 0, trees for normal: 8, total trees: 8
2020-08-26 18:32:10,134  pychop3d.search  [INFO]  normal index: 1, trees for normal: 12, total trees: 20
2020-08-26 18:32:12,403  pychop3d.search  [INFO]  normal index: 2, trees for normal: 10, total trees: 30
2020-08-26 18:32:14,695  pychop3d.search  [INFO]  normal index: 3, trees for normal: 10, total trees: 40
2020-08-26 18:32:17,604  pychop3d.search  [INFO]  normal index: 4, trees for normal: 13, total trees: 53
2020-08-26 18:32:20,084  pychop3d.search  [INFO]  normal index: 5, trees for normal: 8, total trees: 61
2020-08-26 18:32:22,501  pychop3d.search  [INFO]  normal index: 6, trees for normal: 7, total trees: 68
2020-08-26 18:32:25,200  pychop3d.search  [INFO]  normal index: 7, trees for normal: 9, total trees: 77
2020-08-26 18:32:27,741  pychop3d.search  [INFO]  normal index: 8, trees for normal: 10, total trees: 87
2020-08-26 18:32:30,414  pychop3d.search  [INFO]  normal index: 9, trees for normal: 10, total trees: 97
2020-08-26 18:32:33,086  pychop3d.search  [INFO]  normal index: 10, trees for normal: 10, total trees: 107
2020-08-26 18:32:35,803  pychop3d.search  [INFO]  normal index: 11, trees for normal: 9, total trees: 116
2020-08-26 18:32:38,550  pychop3d.search  [INFO]  normal index: 12, trees for normal: 9, total trees: 125
2020-08-26 18:32:41,350  pychop3d.search  [INFO]  normal index: 13, trees for normal: 7, total trees: 132
2020-08-26 18:32:44,332  pychop3d.search  [INFO]  normal index: 14, trees for normal: 7, total trees: 139
2020-08-26 18:32:47,295  pychop3d.search  [INFO]  normal index: 15, trees for normal: 7, total trees: 146
2020-08-26 18:32:50,598  pychop3d.search  [INFO]  normal index: 16, trees for normal: 5, total trees: 151
2020-08-26 18:32:54,378  pychop3d.search  [INFO]  normal index: 17, trees for normal: 10, total trees: 161
2020-08-26 18:32:57,901  pychop3d.search  [INFO]  normal index: 18, trees for normal: 9, total trees: 170
2020-08-26 18:33:01,170  pychop3d.search  [INFO]  normal index: 19, trees for normal: 8, total trees: 178
2020-08-26 18:33:04,720  pychop3d.search  [INFO]  normal index: 20, trees for normal: 7, total trees: 185
2020-08-26 18:33:07,606  pychop3d.search  [INFO]  normal index: 21, trees for normal: 5, total trees: 190
2020-08-26 18:33:10,304  pychop3d.search  [INFO]  normal index: 22, trees for normal: 5, total trees: 195
2020-08-26 18:33:12,977  pychop3d.search  [INFO]  normal index: 23, trees for normal: 5, total trees: 200
2020-08-26 18:33:16,012  pychop3d.search  [INFO]  normal index: 24, trees for normal: 5, total trees: 205
2020-08-26 18:33:18,304  pychop3d.search  [INFO]  normal index: 25, trees for normal: 4, total trees: 209
2020-08-26 18:33:20,199  pychop3d.search  [INFO]  normal index: 26, trees for normal: 3, total trees: 212
2020-08-26 18:33:22,665  pychop3d.search  [INFO]  normal index: 27, trees for normal: 6, total trees: 218
/usr/local/lib/python3.7/site-packages/trimesh/transformations.py:1907: RuntimeWarning: invalid value encountered in arccos
  return np.arccos(dot if directed else np.fabs(dot))
2020-08-26 18:33:22,898  pychop3d.search  [INFO]  64 valid trees
2020-08-26 18:33:22,903  pychop3d.search  [INFO]  Leaves: 2, best objective: 1.219107792445937, estimated number of parts: 2.0
2020-08-26 18:33:22,924  pychop3d.search  [INFO]  Leaves: 3, best objective: 1.219107792445937, estimated number of parts: 2.0
2020-08-26 18:33:22,945  pychop3d.search  [INFO]  Leaves: 4, best objective: 1.219107792445937, estimated number of parts: 2.0
2020-08-26 18:33:22,965  __main__  [INFO]  Best BSP-tree found in 77.52036261558533 seconds
2020-08-26 18:33:22,972  __main__  [INFO]  finding best connector arrangement
2020-08-26 18:33:22,973  pychop3d.connector  [INFO]  Creating connectors...
2020-08-26 18:33:23,271  pychop3d.connector  [INFO]  Number of connectors: 215
2020-08-26 18:33:23,273  pychop3d.connector  [INFO]  determining connector-cut intersections
2020-08-26 18:33:23,671  pychop3d.connector  [INFO]  determining connector-connector intersections
2020-08-26 18:33:23,676  pychop3d.connector  [INFO]  initial objective: 0.70784492994217
2020-08-26 18:33:25,210  pychop3d.connector  [INFO]  post initialization objective: 0.38393393345959786
2020-08-26 18:34:12,714  pychop3d.connector  [INFO]  final objective: 0.38393393345959786
2020-08-26 18:34:12,717  __main__  [INFO]  Best connector arrangement found in 49.74513602256775 seconds
2020-08-26 18:34:12,722  __main__  [INFO]  inserting 4 connectors...
2020-08-26 18:34:12,725  pychop3d.connector  [INFO]  inserting 4 connectors
2020-08-26 18:34:13,655  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:14,281  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:14,898  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:15,507  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:16,117  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:16,725  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:17,344  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:17,957  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:18,563  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
2020-08-26 18:34:19,176  trimesh  [WARNING]  face_normals incorrect shape, ignoring!
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    run(starter)
  File "main.py", line 70, in run
    tree = connector_placer.insert_connectors(tree, state)
  File "/workspaces/propeller/pychop3d/pychop3d/connector.py", line 157, in insert_connectors
    new_node.children[pi].part = insert_slot(new_node.children[pi].part, slot)
  File "/workspaces/propeller/pychop3d/pychop3d/connector.py", line 188, in insert_slot
    raise Exception("Couldn't insert slot")
Exception: Couldn't insert slot
```

Going to need to look into why this isn't working now 😄 

Edit: Looking into it further I think it is because I have too new of a version of Blender so let me downgrade and let you know

**Comment by afshawnlotfi** [comment]
After this works I can create a Docker container and put an end to this compatibility problem!

**Comment by afshawnlotfi** [comment]
Update: It works in a Docker container finally! I will prepare a Dockerfile and .devcontainer PR if you are interested in merging

Edit: Here you go: https://github.com/gregstarr/pychop3d/pull/33
