### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by raould** [gregstarr/pychop3d#45]
I've looked online and tried some of the hack-arounds people mention but I have not been able to get this to work. Has anybody else come across this perhaps, have any thoughts on fixes? 

```
(venv) D:\Dev\pychop3d>python -V
Python 3.7.9

(venv) D:\Dev\pychop3d>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19043 N/A Build 19043

(venv) D:\Dev\pychop3d>python main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from pychop3d.search import beam_search
  File "D:\Dev\pychop3d\pychop3d\search.py", line 2, in <module>
    import trimesh
  File "D:\Dev\pychop3d\venv\lib\site-packages\trimesh\__init__.py", line 15, in <module>
    from .base import Trimesh
  File "D:\Dev\pychop3d\venv\lib\site-packages\trimesh\base.py", line 9, in <module>
    from . import ray
  File "D:\Dev\pychop3d\venv\lib\site-packages\trimesh\ray\__init__.py", line 1, in <module>
    from .import ray_triangle
  File "D:\Dev\pychop3d\venv\lib\site-packages\trimesh\ray\ray_triangle.py", line 7, in <module>
    from .ray_util import contains_points
  File "D:\Dev\pychop3d\venv\lib\site-packages\trimesh\ray\ray_util.py", line 4, in <module>
    from .. import bounds
  File "D:\Dev\pychop3d\venv\lib\site-packages\trimesh\bounds.py", line 5, in <module>
    from . import convex
  File "D:\Dev\pychop3d\venv\lib\site-packages\trimesh\convex.py", line 21, in <module>
    from scipy import spatial
  File "D:\Dev\pychop3d\venv\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "D:\Dev\pychop3d\venv\lib\site-packages\scipy\_distributor_init.py", line 62, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by gregstarr** [comment]
Have you tried posting this on the trimesh github?
