### ISSUE TITLE
Exception: No valid chops found

### ISSUE THREAD

**Issue by marios-stam** [gregstarr/pychop3d#48]
Hello, I try to run `main.py` without chnaging anything and I get the following:

```
Using config: examples/bunny_config.yml
Using mesh: examples/Bunny-LowPoly.stl
2022-12-22 14:47:39,844  pychop3d.search  [INFO]  Starting beam search with an instance of <class 'trimesh.base.Trimesh'>
2022-12-22 14:47:39,844  pychop3d.search  [INFO]  Trimesh stats:
2022-12-22 14:47:39,845  pychop3d.search  [INFO]  verts: 148 extents: [216.24559021 173.24991608 214.51951694]

2022-12-22 14:47:42,280  pychop3d.search  [INFO]  index 0, normal [-0.809  0.588  0.   ], norm trees: 0
2022-12-22 14:47:42,280  pychop3d.search  [INFO]  index 1, normal [-0.793  0.576  0.2  ], norm trees: 0
2022-12-22 14:47:42,280  pychop3d.search  [INFO]  index 2, normal [-0.741  0.539  0.4  ], norm trees: 0
2022-12-22 14:47:42,280  pychop3d.search  [INFO]  index 3, normal [-0.647  0.47   0.6  ], norm trees: 0
2022-12-22 14:47:42,280  pychop3d.search  [INFO]  index 4, normal [-0.485  0.353  0.8  ], norm trees: 0
2022-12-22 14:47:42,280  pychop3d.search  [INFO]  index 5, normal [-0.309  0.951  0.   ], norm trees: 0
2022-12-22 14:47:42,280  pychop3d.search  [INFO]  index 6, normal [-0.303  0.932  0.2  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 7, normal [-0.283  0.872  0.4  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 8, normal [-0.279 -0.253  0.926], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 9, normal [-0.247  0.761  0.6  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 10, normal [-0.185  0.571  0.8  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 11, normal [-0.017 -0.963 -0.268], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 12, normal [0.185 0.571 0.8  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 13, normal [0.247 0.761 0.6  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 14, normal [0.283 0.872 0.4  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 15, normal [0.303 0.932 0.2  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 16, normal [0.309 0.951 0.   ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 17, normal [0.485 0.353 0.8  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 18, normal [0.6 0.  0.8], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 19, normal [0.647 0.47  0.6  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 20, normal [0.741 0.539 0.4  ], norm trees: 0
2022-12-22 14:47:42,281  pychop3d.search  [INFO]  index 21, normal [0.793 0.576 0.2  ], norm trees: 0
2022-12-22 14:47:42,282  pychop3d.search  [INFO]  index 22, normal [0.8 0.  0.6], norm trees: 0
2022-12-22 14:47:42,282  pychop3d.search  [INFO]  index 23, normal [0.809 0.588 0.   ], norm trees: 0
2022-12-22 14:47:42,282  pychop3d.search  [INFO]  index 24, normal [0.917 0.    0.4  ], norm trees: 0
2022-12-22 14:47:42,282  pychop3d.search  [INFO]  index 25, normal [ 0.96  -0.09   0.265], norm trees: 0
2022-12-22 14:47:42,282  pychop3d.search  [INFO]  index 26, normal [0.98 0.   0.2 ], norm trees: 0
2022-12-22 14:47:42,282  pychop3d.search  [INFO]  index 27, normal [1. 0. 0.], norm trees: 0
2022-12-22 14:47:42,282  pychop3d.search  [INFO]  total trees: 0
2022-12-22 14:47:42,282  pychop3d.search  [INFO]  0 valid trees
Traceback (most recent call last):
  File "/home/marios/Desktop/MARIOS/phd/CollaborativeStructure/pychop3d/main.py", line 112, in <module>
    run(starter)
  File "/home/marios/Desktop/MARIOS/phd/CollaborativeStructure/pychop3d/main.py", line 45, in run
    tree = beam_search(starter)
  File "/home/marios/Desktop/MARIOS/phd/CollaborativeStructure/pychop3d/pychop3d/search.py", line 110, in beam_search
    raise Exception("No valid chops found")
Exception: No valid chops found
```
Could you please help me?

**Comment by marios-stam** [comment]
It seems that Rtree library was not properly set and despite that there was no error. Maybe a warning would help future users.
Keep up the good work!
